# Generated by Django 3.2.5 on 2021-07-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='studentSubjects',
            field=models.ManyToManyField(to='SchoolApp.Subject'),
        ),
    ]
