# Generated by Django 3.2.5 on 2021-07-25 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0002_student_studentsubjects'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grade',
            old_name='GradeName',
            new_name='gradeName',
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacherSubjects',
            field=models.ManyToManyField(to='SchoolApp.Subject'),
        ),
    ]
