# Generated by Django 3.2.5 on 2021-07-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolApp', '0004_auto_20210726_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='classRoomName',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='gradeName',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentGrade',
            field=models.CharField(default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentName',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentSubjects',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='classRoomName',
            field=models.CharField(default='', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subjectName',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacherName',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacherSubjects',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
